### ISSUE TITLE
Hi, I have this issue

### ISSUE THREAD

**Issue by Eddy202208** [zinuok/VINS-Fusion-ROS2#2] opened 2022-07-26 10:46 UTC
ros2 launch vins vins_rviz.launch.xml
Package 'vins' not found: "package 'vins' not found, searching: ['/opt/ros/humble']"

**Comment by zinuok** [comment] 2022-07-26 10:54
Hello, 
I have been developing and testing in foxy version.
Therefore, I am not sure if the error is caused by the ros2 version difference. (But that's unlikely, as you know.)

First, did you properly build and source your workspace as follows?
```bash
colcon build --symlink-install && source ./install/setup.bash && source ./install/local_setup.bash
```

First, check whether the built binary file in your workspace is executed.
For that, please refer [here](https://github.com/zinuok/VINS-Fusion-ROS2/tree/4392e34a509c84b5995d0ccdc72decaac868cee7#run).

**Comment by Eddy202208** [comment] 2022-07-26 12:01
Hi, thanks for your reply, well...inside the install folder there is not a folder called vins, that folder is outside but inside it does not have the bin folder, and yes I built the address well

**Comment by Eddy202208** [comment] 2022-07-26 12:02
Hi I sent you a screenshot, thank you

**Comment by zinuok** [comment] 2022-07-28 13:08
Sorry for the late reply.

That's weird.
I tried to rebuild this repository on another ROS2-foxy machine just in case, and it worked fine.

Can you find other ROS2 packages you built manually (not via sudo apt install) in the install folder and run them with ros2 run/launch command?
Or maybe you can test it on foxy.
Sorry for not being of much help.

**Comment by zinuok** [comment] 2022-07-29 01:06
Hello,
I've updated the README.md regarding the clone and build path.
Please refer to [this](https://github.com/zinuok/VINS-Fusion-ROS2/blob/main/README.md#build) and try again.

Thank you

**Comment by Eddy202208** [comment] 2022-07-29 15:38
Hi sorry for the delay, I edited the real_sense file and it looks like this: 


#######################
## ROS2 dependencies ##
#######################
sudo apt-get install -y ros-humble-cv-bridge ros-humble-librealsense2 ros-humble-message-filters ros-humble-image-transport
sudo apt-get install -y libssl-dev libusb-1.0-0-dev pkg-config libgtk-3-dev
sudo apt-get install -y libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev

###################
## Realsense SDK ##
###################
# Register the server's public key:
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE

# Add the server to the list of repositories:
sudo add-apt-repository "deb https://librealsense.intel.com/Debian/apt-repo $(lsb_release -cs) main" -u

# Install the libraries (see section below if upgrading packages):
sudo apt-get -y install librealsense2-dkms && sudo apt-get -y install librealsense2-utils

# Optionally install the developer and debug packages:
sudo apt-get install -y librealsense2-dev && sudo apt-get install -y librealsense2-dbg


####################
## ROS2 realsense ##
####################
cd ~/ros2_ws/src
git clone --depth 1 --branch `git ls-remote --tags https://github.com/IntelRealSense/realsense-ros.git | grep -Po "(?<=tags/)3.\d+\.\d+" | sort -V | tail -1` https://github.com/IntelRealSense/realsense-ros.git
cd ..

## install dependencies
sudo apt-get install python3-rosdep -y
sudo rosdep init # "sudo rosdep init --include-eol-distros" for Dashing
rosdep update
rosdep install -i --from-path src --rosdistro $ROS_DISTRO --skip-keys=librealsense2 -y

# build
colcon build --symlink-install



Now I will try the rest and see if it works, I will keep you posted.

**Comment by Eddy202208** [comment] 2022-07-30 01:03
Hi, sorry for the late reply, I got this error (I'm using Ubuntu 20.04, ROS2 Foxy):

~/ros2_ws/src$ colcon build --symlink-install && source ./install/setup.bash && source ./install/local_setup.bash
Starting >>> camera_models
Starting >>> realsense2_camera_msgs
Starting >>> global_fusion
--- stderr: camera_models                                         
CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "Findament_cmake.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "ament_cmake", but CMake did not find one.

  Could not find a package configuration file provided by "ament_cmake" with
  any of the following names:

    ament_cmakeConfig.cmake
    ament_cmake-config.cmake

  Add the installation prefix of "ament_cmake" to CMAKE_PREFIX_PATH or set
  "ament_cmake_DIR" to a directory containing one of the above files.  If
  "ament_cmake" provides a separate development package or SDK, be sure it
  has been installed.


---
Failed   <<< camera_models [0.43s, exited with code 1]
Aborted  <<< realsense2_camera_msgs [0.42s]
Aborted  <<< global_fusion [0.41s]

Summary: 0 packages finished [0.58s]
  1 package failed: camera_models
  2 packages aborted: global_fusion realsense2_camera_msgs
  3 packages had stderr output: camera_models global_fusion realsense2_camera_msgs
  4 packages not processed

**Comment by Eddy202208** [comment] 2022-07-30 02:31
Hi, sorry for the late reply, I got this error (I'm using Ubuntu 20.04, ROS2 Foxy):

~/ros/ros2_ws/src/VINS-Fusion-ROS2$ bash realsense_install.sh
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ros-foxy-cv-bridge is already the newest version (2.2.1-1focal.20220209.150123).
ros-foxy-image-transport is already the newest version (2.3.0-1focal.20220209.153003).
ros-foxy-librealsense2 is already the newest version (2.50.0-2focal.20220223.160142).
ros-foxy-message-filters is already the newest version (3.2.5-1focal.20220209.150609).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1
  libgstreamer-plugins-bad1.0-0 libva-wayland2
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libusb-1.0-0-dev is already the newest version (2:1.0.23-2build1).
pkg-config is already the newest version (0.29.1-0ubuntu4).
libgtk-3-dev is already the newest version (3.24.20-0ubuntu1.1).
libssl-dev is already the newest version (1.1.1f-1ubuntu2.16).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1
  libgstreamer-plugins-bad1.0-0 libva-wayland2
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libglu1-mesa-dev is already the newest version (9.0.1-1build1).
libglfw3-dev is already the newest version (3.3.2-1).
libgl1-mesa-dev is already the newest version (21.2.6-0ubuntu0.1~20.04.2).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1
  libgstreamer-plugins-bad1.0-0 libva-wayland2
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Executing: /tmp/apt-key-gpghome.HCK3CV5h6G/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
gpg: key C8B3A55A6F3EFCDE: ""CN = Intel(R) Intel(R) Realsense", O=Intel Corporation" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Hit:1 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 https://brave-browser-apt-release.s3.brave.com stable InRelease          
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease                         
Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease                 
Hit:5 http://packages.ros.org/ros2/ubuntu focal InRelease                      
Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:7 http://archive.ubuntu.com/ubuntu focal-security InRelease
Hit:8 https://librealsense.intel.com/Debian/apt-repo focal InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
librealsense2-dkms is already the newest version (1.3.18-0ubuntu1).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1
  libgstreamer-plugins-bad1.0-0 libva-wayland2
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
librealsense2-utils is already the newest version (2.50.0-0~realsense0.6128).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1
  libgstreamer-plugins-bad1.0-0 libva-wayland2
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
librealsense2-dev is already the newest version (2.50.0-0~realsense0.6128).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1
  libgstreamer-plugins-bad1.0-0 libva-wayland2
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
librealsense2-dbg is already the newest version (2.50.0-0~realsense0.6128).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1
  libgstreamer-plugins-bad1.0-0 libva-wayland2
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
fatal: destination path 'realsense-ros' already exists and is not an empty directory.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-rosdep is already the newest version (0.22.1-1).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1
  libgstreamer-plugins-bad1.0-0 libva-wayland2
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
ERROR: default sources list file already exists:
	/etc/ros/rosdep/sources.list.d/20-default.list
Please delete if you wish to re-initialize
reading in sources list data from /etc/ros/rosdep/sources.list.d
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
Skip end-of-life distro "ardent"
Skip end-of-life distro "bouncy"
Skip end-of-life distro "crystal"
Skip end-of-life distro "dashing"
Skip end-of-life distro "eloquent"
Add distro "foxy"
Add distro "galactic"
Skip end-of-life distro "groovy"
Add distro "humble"
Skip end-of-life distro "hydro"
Skip end-of-life distro "indigo"
Skip end-of-life distro "jade"
Skip end-of-life distro "kinetic"
Skip end-of-life distro "lunar"
Add distro "melodic"
Add distro "noetic"
Add distro "rolling"
updated cache in /home/cfa/.ros/rosdep/sources.cache
#All required rosdeps installed successfully
Starting >>> realsense2_camera_msgs
--- stderr: realsense2_camera_msgs                         
CMake Error at /opt/ros/foxy/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:60 (message):
  execute_process(/home/cfa/anaconda3/bin/python3 -m rosidl_adapter
  --package-name realsense2_camera_msgs --arguments-file
  /home/cfa/ros/catkin_ws/build/realsense2_camera_msgs/rosidl_adapter__arguments__realsense2_camera_msgs.json
  --output-dir
  /home/cfa/ros/catkin_ws/build/realsense2_camera_msgs/rosidl_adapter/realsense2_camera_msgs
  --output-file
  /home/cfa/ros/catkin_ws/build/realsense2_camera_msgs/rosidl_adapter/realsense2_camera_msgs.idls)
  returned error code 1:

  AttributeError processing template 'msg.idl.em'

  Traceback (most recent call last):

    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/resource/__init__.py", line 48, in evaluate_template
      _interpreter = em.Interpreter(

  AttributeError: module 'em' has no attribute 'Interpreter'

  

  During handling of the above exception, another exception occurred:

  

  Traceback (most recent call last):

    File "/home/cfa/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/home/cfa/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/msg/__init__.py", line 39, in convert_msg_to_idl
      expand_template('msg.idl.em', data, output_file, encoding='iso-8859-1')
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/resource/__init__.py", line 23, in expand_template
      content = evaluate_template(template_name, data)
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/resource/__init__.py", line 69, in evaluate_template
      _interpreter.shutdown()

  AttributeError: 'NoneType' object has no attribute 'shutdown'

Call Stack (most recent call first):
  /opt/ros/foxy/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:23 (rosidl_generate_interfaces)


---
Failed   <<< realsense2_camera_msgs [0.60s, exited with code 1]
                                
Summary: 0 packages finished [0.77s]
  1 package failed: realsense2_camera_msgs
  1 package had stderr output: realsense2_camera_msgs
  2 packages not processed

**Comment by Eddy202208** [comment] 2022-07-30 02:35
Hi, sorry for the late reply, I got this error (I'm using Ubuntu 20.04, ROS2 Foxy):

~/ros/ros2_ws/src/VINS-Fusion-ROS2$ bash realsense_install.sh
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ros-foxy-cv-bridge is already the newest version (2.2.1-1focal.20220209.150123).
ros-foxy-image-transport is already the newest version (2.3.0-1focal.20220209.153003).
ros-foxy-librealsense2 is already the newest version (2.50.0-2focal.20220223.160142).
ros-foxy-message-filters is already the newest version (3.2.5-1focal.20220209.150609).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1
  libgstreamer-plugins-bad1.0-0 libva-wayland2
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libusb-1.0-0-dev is already the newest version (2:1.0.23-2build1).
pkg-config is already the newest version (0.29.1-0ubuntu4).
libgtk-3-dev is already the newest version (3.24.20-0ubuntu1.1).
libssl-dev is already the newest version (1.1.1f-1ubuntu2.16).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1
  libgstreamer-plugins-bad1.0-0 libva-wayland2
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libglu1-mesa-dev is already the newest version (9.0.1-1build1).
libglfw3-dev is already the newest version (3.3.2-1).
libgl1-mesa-dev is already the newest version (21.2.6-0ubuntu0.1~20.04.2).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1
  libgstreamer-plugins-bad1.0-0 libva-wayland2
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Executing: /tmp/apt-key-gpghome.HCK3CV5h6G/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
gpg: key C8B3A55A6F3EFCDE: ""CN = Intel(R) Intel(R) Realsense", O=Intel Corporation" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Hit:1 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 https://brave-browser-apt-release.s3.brave.com stable InRelease          
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease                         
Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease                 
Hit:5 http://packages.ros.org/ros2/ubuntu focal InRelease                      
Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:7 http://archive.ubuntu.com/ubuntu focal-security InRelease
Hit:8 https://librealsense.intel.com/Debian/apt-repo focal InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
librealsense2-dkms is already the newest version (1.3.18-0ubuntu1).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1
  libgstreamer-plugins-bad1.0-0 libva-wayland2
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
librealsense2-utils is already the newest version (2.50.0-0~realsense0.6128).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1
  libgstreamer-plugins-bad1.0-0 libva-wayland2
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
librealsense2-dev is already the newest version (2.50.0-0~realsense0.6128).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1
  libgstreamer-plugins-bad1.0-0 libva-wayland2
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
librealsense2-dbg is already the newest version (2.50.0-0~realsense0.6128).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1
  libgstreamer-plugins-bad1.0-0 libva-wayland2
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
fatal: destination path 'realsense-ros' already exists and is not an empty directory.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-rosdep is already the newest version (0.22.1-1).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libfwupdplugin1
  libgstreamer-plugins-bad1.0-0 libva-wayland2
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
ERROR: default sources list file already exists:
	/etc/ros/rosdep/sources.list.d/20-default.list
Please delete if you wish to re-initialize
reading in sources list data from /etc/ros/rosdep/sources.list.d
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
Skip end-of-life distro "ardent"
Skip end-of-life distro "bouncy"
Skip end-of-life distro "crystal"
Skip end-of-life distro "dashing"
Skip end-of-life distro "eloquent"
Add distro "foxy"
Add distro "galactic"
Skip end-of-life distro "groovy"
Add distro "humble"
Skip end-of-life distro "hydro"
Skip end-of-life distro "indigo"
Skip end-of-life distro "jade"
Skip end-of-life distro "kinetic"
Skip end-of-life distro "lunar"
Add distro "melodic"
Add distro "noetic"
Add distro "rolling"
updated cache in /home/eddy/.ros/rosdep/sources.cache
#All required rosdeps installed successfully
Starting >>> realsense2_camera_msgs
--- stderr: realsense2_camera_msgs                         
CMake Error at /opt/ros/foxy/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:60 (message):
  execute_process(/home/eddy/anaconda3/bin/python3 -m rosidl_adapter
  --package-name realsense2_camera_msgs --arguments-file
  /home/eddy/ros/catkin_ws/build/realsense2_camera_msgs/rosidl_adapter__arguments__realsense2_camera_msgs.json
  --output-dir
  /home/eddy/ros/catkin_ws/build/realsense2_camera_msgs/rosidl_adapter/realsense2_camera_msgs
  --output-file
  /home/eddy/ros/catkin_ws/build/realsense2_camera_msgs/rosidl_adapter/realsense2_camera_msgs.idls)
  returned error code 1:

  AttributeError processing template 'msg.idl.em'

  Traceback (most recent call last):

    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/resource/__init__.py", line 48, in evaluate_template
      _interpreter = em.Interpreter(

  AttributeError: module 'em' has no attribute 'Interpreter'

  
  During handling of the above exception, another exception occurred:

  
  Traceback (most recent call last):

    File "/home/eddy/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/home/eddy/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/msg/__init__.py", line 39, in convert_msg_to_idl
      expand_template('msg.idl.em', data, output_file, encoding='iso-8859-1')
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/resource/__init__.py", line 23, in expand_template
      content = evaluate_template(template_name, data)
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/resource/__init__.py", line 69, in evaluate_template
      _interpreter.shutdown()

  AttributeError: 'NoneType' object has no attribute 'shutdown'

Call Stack (most recent call first):
  /opt/ros/foxy/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:23 (rosidl_generate_interfaces)


---
Failed   <<< realsense2_camera_msgs [0.60s, exited with code 1]
                                
Summary: 0 packages finished [0.77s]
  1 package failed: realsense2_camera_msgs
  1 package had stderr output: realsense2_camera_msgs
  2 packages not processed

**Comment by Eddy202208** [comment] 2022-07-30 04:11
Hi there sorry for the late reply, and thank you for your help (I was able to install everything thanks to you), however I have this questions:

First question:
# vins
ros2 run vins $(PATH_TO_YOUR_VINS_CONFIG_FILE)

could you help me here, I want to use the EUROC dataset, this is the path to my vins config file
/home/eddy/ros/ros2_ws/src/VINS-Fusion-ROS2/config/euroc
But I don't know how to make it work

Second question:
ros2 launch vins vins_rviz.launch.xml
This code works, but when RVIZ2 opens I can't see the drone
![Screenshot from 2022-07-30 01-05-45](https://user-images.githubusercontent.com/100820346/181871773-f6d9051f-e8aa-4ee2-b6bb-c1b56aba9270.png)

And third question 
export PATH=$PATH:~/.local/bin
rosbags-convert foo.bag --dst /path/to/bar
I don't understand what to do

Sorry for all the problems, I'm new in ROS

**Comment by zinuok** [comment] 2022-07-31 10:49
`For the first question,`

Your question already contains the proper answer!
The only thing you have to do is just pass the path to the YAML config file as an argument to your vins program.
For example, in your case, (let's assume that you want execute the VINS with stereo camera + IMU setup)
```bash
ros2 run vins /home/eddy/ros/ros2_ws/src/VINS-Fusion-ROS2/config/euroc/euroc_stereo_imu_config.yaml
```

-------

`For the second question,`

It seems that an error occurred in the process of Rviz recognizing the config file, and the saved configuration could not be loaded.
Then, you have to manually add the `trajectory` topic (maybe named as /vins_estimator/trajectory or /trajectory). 
You can click the ```Add``` button at the bottom left for this action.
Please note that the Rviz is just a visualization tool, and the essential topic from the VINS is normally published.

-------

`And for the last question,` 

In the following command statement, 
```bash
rosbags-convert foo.bag --dst /path/to/bar
```
`foo.bag` is the bag recorded from ROS1, and the `/path/to/bar` is the output folder name combined with its path for ROS2.
In ROS2, rosbag exists in the form of a folder wherein metadata is included.
For test, you can download the EuRoC ros1 bag file from [here](https://projects.asl.ethz.ch/datasets/doku.php?id=kmavvisualinertialdatasets) and try to convert it to your own `/path/to/bar`.

-------

I can't explain to you all the basics of the ROS here.
For that, I think [this link](https://docs.ros.org/en/foxy/Tutorials.html) will help you.

Sincerely,
Jinwoo Jeon

**Comment by Eddy202208** [comment] 2022-07-31 14:40
Hi thanks again well, the first error i got this:
ros2 run vins /home/eddy/ros/ros2_ws/src/VINS-Fusion-ROS2/config/euroc/euroc_stereo_imu_config.yaml
No executable found

And the second one I don't know what do I have to add, I got this:

![Screenshot from 2022-07-31 11-31-00](https://user-images.githubusercontent.com/100820346/182031524-28512091-bc98-4c3c-9a04-d17b7032b9c8.png)

![Screenshot from 2022-07-31 11-31-04](https://user-images.githubusercontent.com/100820346/182031526-1302ff63-f0ef-4240-9b37-3497a1242dd3.png)

**Comment by zinuok** [comment] 2022-08-01 03:27
- A1.
Didn't you say that it was successfully installed at [Question](https://github.com/zinuok/VINS-Fusion-ROS2/issues/2#issuecomment-1200083942)? 
It doesn't make sense to not be able to find the executable file after a successful install. 
Or I want to ask if you didn't build and source it.
Whenever a new package is built, you need to source ```setup.bash``` in the install folder.

-----

- A2.
In Rviz, you can visualize your topic by clicking the ```By topic```. Just click the proper button corresponding to the trajectory topic, such as ```/vins_estimator/trajectory```. That's all!

**Comment by Eddy202208** [comment] 2022-08-01 09:22
Ok, I will show you step by step

~/ros/ros2_ws/src/VINS-Fusion-ROS2$ colcon build --symlink-install && source ./install/setup.bash && source ./install/local_setup.bash
Starting >>> camera_models
Starting >>> global_fusion
Finished <<< global_fusion [0.27s]                                     
Finished <<< camera_models [0.31s]                  
Starting >>> loop_fusion
Starting >>> vins
Finished <<< loop_fusion [0.26s]                                  
Finished <<< vins [0.33s]                  

Summary: 4 packages finished [0.83s]

~/ros/ros2_ws/src/VINS-Fusion-ROS2$ source /opt/ros/foxy/setup.bash

~/ros/ros2_ws/src/VINS-Fusion-ROS2$ ros2 run vins /home/eddy/ros/ros2_ws/src/VINS-Fusion-ROS2/config/euroc/euroc_stereo_imu_config.yaml
No executable found

That's all


However I did this now:

ros2 run vins **vins_node** /home/eddy/ros/ros2_ws/src/VINS-Fusion-ROS2/config/euroc/euroc_stereo_imu_config.yaml

And this is what I got:

[INFO] [1659345358.397222992] []: init begins
config_file: /home/eddy/ros/ros2_ws/src/VINS-Fusion-ROS2/config/euroc/euroc_stereo_imu_config.yaml
USE_IMU: 1
IMU_TOPIC: /imu0
result path ~/home/eddy/ros/output//vio.csv
[WARN] [1659345358.510779428] []:  fix extrinsic param 
camera number 2
[INFO] [1659345358.513451225] []: Synchronized sensors, fix time offset: 0.000000
[INFO] [1659345358.514442774] []: ROW: 480 COL: 752 
 exitrinsic cam 0
 0.0148655  -0.999881  0.0041403
  0.999557  0.0149672  0.0257155
-0.0257744 0.00375619   0.999661
-0.0216401  -0.064677 0.00981073
 exitrinsic cam 1
 0.0125553  -0.999755  0.0182238
  0.999599  0.0130119  0.0251588
-0.0253898  0.0179006   0.999517
-0.0198436  0.0453689 0.00786212
set g       0       0 9.81007
[INFO] [1659345358.514567022] []: reading paramerter of camera /home/eddy/ros/ros2_ws/src/VINS-Fusion-ROS2/config/euroc/cam0_mei.yaml
[INFO] [1659345358.516301647] []: reading paramerter of camera /home/eddy/ros/ros2_ws/src/VINS-Fusion-ROS2/config/euroc/cam1_mei.yaml
MULTIPLE_THREAD is 1
[WARN] [1659345358.516672026] []: waiting for image and imu...

**Comment by zinuok** [comment] 2022-08-01 10:41
Oh sorry for my mistake
At [my previous answer](https://github.com/zinuok/VINS-Fusion-ROS2/issues/2#issuecomment-1200399270),
the command should be 

```bash
ros2 run vins vins_node /home/eddy/ros/ros2_ws/src/VINS-Fusion-ROS2/config/euroc/euroc_stereo_imu_config.yaml
```
The `vins` and `vins_node` stand for the package name and executable node name, respectively.

Thank you

**Comment by Eddy202208** [comment] 2022-08-01 13:11
No problem, you are being a great help, I don't know what this means.

WARN] [1659358864.484874572] []: waiting for image and imu...

But still, suppose I want to run kitti's code now I guess it would be:

ros2 run vins vins_node /home/eddy/ros/ros2_ws/src/VINS-Fusion-ROS2/config/kitti_odom/kitti_config00-02.yaml

The next step would be:

ros2 launch vins vins vins_rviz.launch.xml

When you refer to trajectory or vins_estimator/trajectory is the folder where I save the trajectory for either KITTI or EUROC ? and in that case it would be like this ?

ros2 run vins vins vins_node /home/eddy/ros/ros2_ws/src/VINS-Fusion-ROS2/config/kitti_odom/kitti_config00-02.yaml YOUR_DATASET_FOLDER/sequences/

**Comment by Eddy202208** [comment] 2022-08-01 13:13
No problem, you are being a great help, I don't know what this means:

WARN] [1659358864.484874572] []: waiting for image and imu...

But still, suppose I want to run kitti's code now I guess it would be:

`ros2 run vins vins_node /home/eddy/ros/ros2_ws/src/VINS-Fusion-ROS2/config/kitti_odom/kitti_config00-02.yaml`

The next step would be:

ros2 launch vins vins_rviz.launch.xml

When you refer to trajectory or vins_estimator/trajectory is the folder where I save the trajectory for either KITTI or EUROC ? and in that case it would be like this ?
`
ros2 run vins vins vins_node /home/eddy/ros/ros2_ws/src/VINS-Fusion-ROS2/config/kitti_odom/kitti_config00-02.yaml YOUR_DATASET_FOLDER/sequences/`

**Comment by Eddy202208** [comment] 2022-08-01 13:15
No problem, you are being a great help, I don't know what this means:

WARN] [1659358864.484874572] []: waiting for image and imu...

But still, suppose I want to run kitti's code now I guess it would be:

`ros2 run vins vins_node /home/eddy/ros/ros2_ws/src/VINS-Fusion-ROS2/config/kitti_odom/kitti_config00-02.yaml`

The next step would be:

`ros2 launch vins vins_rviz.launch.xml`

When you refer to trajectory or `vins_estimator/trajectory` is the folder where I have to save the trajectory for either KITTI or EUROC ? and in that case it would be like this ?

`ros2 run vins vins vins_node /home/eddy/ros/ros2_ws/src/VINS-Fusion-ROS2/config/kitti_odom/kitti_config00-02.yaml YOUR_DATASET_FOLDER/sequences/`

**Comment by zinuok** [comment] 2022-08-01 13:34
No, the `trajectory` topic I mentioned is not the concept of being stored in a physical folder. 
Please refer [here](https://github1s.com/zinuok/VINS-Fusion-ROS2/blob/HEAD/vins/src/utility/visualization.cpp#L37-L38) for the implementation. (its accurate name in the code is, therefore, `/path` or `/vins_estimator/path`).
You could find it via:
```bash
ros2 topic list
ros2 topic echo $(TOPIC_NAME)
```

I think you should study the [basic ROS2 topic concept](https://docs.ros.org/en/foxy/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Topics/Understanding-ROS2-Topics.html).

Keep in mind that you should learn the basics of ROS / ROS2 yourself, before using this repo.

**Comment by zinuok** [comment] 2022-08-03 14:03
I think the question has been resolved, so I'm closing this issue.

Feel free to reopen this or post a new issue.
Thank you!

**Closed by zinuok** 2022-08-03 14:03 UTC
